language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install: pip install tox flake8 tox-travis
sudo: false
script: tox
before_script:
 - flake8 django_password_protect tests --ignore=E501,E128,E402
